export const tagColors = {
  Fintech: "bg-blue-100 text-blue-600",
  "Payment gateway": "bg-purple-100 text-purple-600",
  Technology: "bg-gray-100 text-gray-600",
  AI: "bg-red-100 text-red-600",
  "E-commerce": "bg-yellow-100 text-yellow-600",
  Telecom: "bg-green-100 text-green-600",
  Banking: "bg-indigo-100 text-indigo-600",
  Aviation: "bg-teal-100 text-teal-600",
};

export const companiesData = [
  {
    name: "eSewa",
    icon: "/jobs/sample.png",
    description: "eSewa is Nepal's leading digital payment platform...",
    tags: ["Fintech", "Payment gateway"],
    jobs: 12,
    industry: "Fintech",
    companySize: "251-500",
  },
  {
    name: "Khalti",
    icon: "/jobs/sample.png",
    description: "Khalti is a digital wallet providing payment solutions...",
    tags: ["Fintech", "Payment gateway"],
    jobs: 8,
    industry: "Fintech",
    companySize: "151-250",
  },
  {
    name: "CloudFactory",
    icon: "/jobs/sample.png",
    description: "CloudFactory provides workforce solutions for AI...",
    tags: ["Technology", "AI"],
    jobs: 15,
    industry: "Technology",
    companySize: "501-1000",
  },
  {
    name: "F1Soft International",
    icon: "/jobs/sample.png",
    description: "Developer of popular digital financial platforms...",
    tags: ["Fintech", "Technology"],
    jobs: 10,
    industry: "Fintech",
    companySize: "251-500",
  },
  {
    name: "Daraz Nepal",
    icon: "/jobs/sample.png",
    description: "Nepal's largest online marketplace...",
    tags: ["E-commerce"],
    jobs: 20,
    industry: "E-commerce",
    companySize: "251-500",
  },
  {
    name: "Nepal Telecom",
    icon: "/jobs/sample.png",
    description: "The largest telecommunications service provider...",
    tags: ["Telecom"],
    jobs: 25,
    industry: "Telecom",
    companySize: "1000-above",
  },
  {
    name: "Nabil Bank",
    icon: "/jobs/sample.png",
    description: "One of Nepal's leading commercial banks...",
    tags: ["Banking"],
    jobs: 18,
    industry: "Banking",
    companySize: "501-1000",
  },
  {
    name: "Yeti Airlines",
    icon: "/jobs/sample.png",
    description: "A premier domestic airline in Nepal...",
    tags: ["Aviation"],
    jobs: 14,
    industry: "Aviation",
    companySize: "501-1000",
  },
  {
    name: "Code Himalaya",
    icon: "/jobs/sample.png",
    description: "Software development company...",
    tags: ["Technology"],
    jobs: 5,
    industry: "Technology",
    companySize: "1-50",
  },
  {
    name: "Leapfrog Technology",
    icon: "/jobs/sample.png",
    description: "Digital product development company...",
    tags: ["Technology"],
    jobs: 7,
    industry: "Technology",
    companySize: "51-150",
  },
  {
    name: "Cotiviti Nepal",
    icon: "/jobs/sample.png",
    description: "Healthcare analytics and payment accuracy...",
    tags: ["Healthcare"],
    jobs: 12,
    industry: "Healthcare",
    companySize: "501-1000",
  },
  {
    name: "Foodmario",
    icon: "/jobs/sample.png",
    description: "Online food delivery platform...",
    tags: ["Food & Beverage"],
    jobs: 8,
    industry: "Food & Beverage",
    companySize: "51-150",
  },
  {
    name: "Fusemachines Nepal",
    icon: "/jobs/sample.png",
    description: "AI solutions provider...",
    tags: ["Technology", "AI"],
    jobs: 9,
    industry: "Technology",
    companySize: "151-250",
  },
  {
    name: "EB Pearls",
    icon: "/jobs/sample.png",
    description: "Digital agency...",
    tags: ["Technology"],
    jobs: 6,
    industry: "Technology",
    companySize: "151-250",
  },
];

export const staticIndustryLabels = [
  "Advertising",
  "Business Service",
  "Blockchain",
  "Cloud",
  "Consumer Tech",
  "Education",
  "Fintech",
  "Gaming",
  "Food & Beverage",
  "Healthcare",
  "Hosting",
];

export const staticCompanySizeLabels = [
  "1-50",
  "51-150",
  "151-250",
  "251-500",
  "501-1000",
  "1000-above",
];
export const locations = [
  "Kathmandu, Nepal",
  "Lalitpur, Nepal",
  "Bhaktapur, Nepal",
  "Pokhara, Nepal",
  "Biratnagar, Nepal",
  "Birgunj, Nepal",
];
