export const tagColors = {
  Marketing: "border-[#FFB836] border-[1px] text-[#FFB836]",
  Design: "border-[#4640DE] border-[1px] text-[#4640DE]",
  Technology: "bg-[#FF65501A] text-[#FF6550]",
  "UI Design": "border-[#00B8D9] border-[1px] text-[#00B8D9]",
  Sales: "border-[#36B37E] border-[1px] text-[#36B37E]",
};

export const jobsData = [
  {
    id: 1,
    title: "Social Media Assistant",
    company: "CloudFactory",
    location: "Kathmandu, Nepal",
    tags: ["Design", "Marketing"],
    applicants: 4,
    capacity: 10,
    type: "Full Time",
    category: "Marketing",
    level: "Entry",
    salary: 40000,
    icon: "/jobs/sample.png",
  },
  {
    id: 2,
    title: "Brand Designer",
    company: "Fusemachines Nepal",
    location: "Lalitpur, Nepal",
    tags: ["Design"],
    applicants: 2,
    capacity: 10,
    type: "Full Time",
    category: "Design",
    level: "Mid",
    salary: 80000,
    icon: "/jobs/sample.png",
  },
  {
    id: 3,
    title: "Interactive Developer",
    company: "Leapfrog Technology",
    location: "Kathmandu, Nepal",
    tags: ["UI Design"],
    applicants: 6,
    capacity: 10,
    type: "Contract",
    category: "Design",
    level: "Senior",
    salary: 120000,
    icon: "/jobs/sample.png",
  },
  {
    id: 4,
    title: "Backend Engineer",
    company: "Code Himalaya",
    location: "Bhaktapur, Nepal",
    tags: ["Technology"],
    applicants: 2,
    capacity: 5,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 95000,
    icon: "/jobs/sample.png",
  },
  {
    id: 5,
    title: "Mobile App Developer",
    company: "EB Pearls",
    location: "Lalitpur, Nepal",
    tags: ["Technology"],
    applicants: 5,
    capacity: 8,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 125000,
    icon: "/jobs/sample.png",
  },
  {
    id: 6,
    title: "Product Manager",
    company: "CloudFactory",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 3,
    capacity: 3,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 180000,
    icon: "/jobs/sample.png",
  },
  {
    id: 7,
    title: "Customer Support Executive",
    company: "Daraz Nepal",
    location: "Lalitpur, Nepal",
    tags: ["Marketing"],
    applicants: 7,
    capacity: 10,
    type: "Full Time",
    category: "Marketing",
    level: "Entry",
    salary: 35000,
    icon: "/jobs/sample.png",
  },
  {
    id: 8,
    title: "Business Analyst",
    company: "F1Soft International",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 4,
    capacity: 5,
    type: "Remote",
    category: "Technology",
    level: "Mid",
    salary: 105000,
    icon: "/jobs/sample.png",
  },
  {
    id: 9,
    title: "Operations Manager",
    company: "Foodmario",
    location: "Kathmandu, Nepal",
    tags: ["Sales", "Marketing"],
    applicants: 3,
    capacity: 2,
    type: "Full Time",
    category: "Marketing",
    level: "Senior",
    salary: 85000,
    icon: "/jobs/sample.png",
  },
  {
    id: 10,
    title: "Digital Marketing Officer",
    company: "Khalti",
    location: "Lalitpur, Nepal",
    tags: ["Marketing"],
    applicants: 6,
    capacity: 6,
    type: "Full Time",
    category: "Marketing",
    level: "Mid",
    salary: 60000,
    icon: "/jobs/sample.png",
  },
  {
    id: 11,
    title: "Sales Officer",
    company: "Nabil Bank",
    location: "Kathmandu, Nepal",
    tags: ["Sales"],
    applicants: 5,
    capacity: 7,
    type: "Full Time",
    category: "Sales",
    level: "Mid",
    salary: 75000,
    icon: "/jobs/sample.png",
  },
  {
    id: 12,
    title: "Flight Operations Coordinator",
    company: "Yeti Airlines",
    location: "Pokhara, Nepal",
    tags: ["Technology"],
    applicants: 2,
    capacity: 2,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 85000,
    icon: "/jobs/sample.png",
  },
  {
    id: 13,
    title: "AI Researcher",
    company: "Fusemachines Nepal",
    location: "Kathmandu, Nepal",
    tags: ["AI", "Technology"],
    applicants: 1,
    capacity: 3,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 200000,
    icon: "/jobs/sample.png",
  },
  {
    id: 14,
    title: "Healthcare Data Analyst",
    company: "Cotiviti Nepal",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 4,
    capacity: 4,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 100000,
    icon: "/jobs/sample.png",
  },
  {
    id: 15,
    title: "Telecom Engineer",
    company: "Nepal Telecom",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 6,
    capacity: 6,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 140000,
    icon: "/jobs/sample.png",
  },
  {
    id: 16,
    title: "Software Tester",
    company: "Leapfrog Technology",
    location: "Lalitpur, Nepal",
    tags: ["Technology"],
    applicants: 3,
    capacity: 4,
    type: "Full Time",
    category: "Technology",
    level: "Entry",
    salary: 70000,
    icon: "/jobs/sample.png",
  },
  {
    id: 17,
    title: "Graphic Designer",
    company: "EB Pearls",
    location: "Lalitpur, Nepal",
    tags: ["Design"],
    applicants: 5,
    capacity: 5,
    type: "Remote",
    category: "Design",
    level: "Mid",
    salary: 60000,
    icon: "/jobs/sample.png",
  },
  {
    id: 18,
    title: "DevOps Engineer",
    company: "Code Himalaya",
    location: "Bhaktapur, Nepal",
    tags: ["Technology"],
    applicants: 1,
    capacity: 2,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 145000,
    icon: "/jobs/sample.png",
  },
  {
    id: 19,
    title: "Content Strategist",
    company: "eSewa",
    location: "Kathmandu, Nepal",
    tags: ["Marketing"],
    applicants: 4,
    capacity: 3,
    type: "Remote",
    category: "Marketing",
    level: "Mid",
    salary: 65000,
    icon: "/jobs/sample.png",
  },
  {
    id: 20,
    title: "Payments Integration Engineer",
    company: "Khalti",
    location: "Lalitpur, Nepal",
    tags: ["Technology"],
    applicants: 3,
    capacity: 3,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 95000,
    icon: "/jobs/sample.png",
  },
  // Newly added jobs below
  {
    id: 21,
    title: "UX Researcher",
    company: "Deerwalk",
    location: "Kathmandu, Nepal",
    tags: ["Design", "Research"],
    applicants: 2,
    capacity: 3,
    type: "Full Time",
    category: "Design",
    level: "Mid",
    salary: 90000,
    icon: "/jobs/sample.png",
  },
  {
    id: 22,
    title: "Cybersecurity Specialist",
    company: "F1Soft International",
    location: "Kathmandu, Nepal",
    tags: ["Technology", "Security"],
    applicants: 1,
    capacity: 2,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 160000,
    icon: "/jobs/sample.png",
  },
  {
    id: 23,
    title: "Technical Writer",
    company: "Leapfrog Technology",
    location: "Lalitpur, Nepal",
    tags: ["Content", "Technology"],
    applicants: 3,
    capacity: 4,
    type: "Remote",
    category: "Content",
    level: "Mid",
    salary: 75000,
    icon: "/jobs/sample.png",
  },
  {
    id: 24,
    title: "HR Manager",
    company: "CloudFactory",
    location: "Kathmandu, Nepal",
    tags: ["HR", "Management"],
    applicants: 5,
    capacity: 1,
    type: "Full Time",
    category: "HR",
    level: "Senior",
    salary: 110000,
    icon: "/jobs/sample.png",
  },
  {
    id: 25,
    title: "Data Scientist",
    company: "Fusemachines Nepal",
    location: "Kathmandu, Nepal",
    tags: ["AI", "Technology"],
    applicants: 2,
    capacity: 3,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 175000,
    icon: "/jobs/sample.png",
  },
  {
    id: 26,
    title: "Frontend Developer",
    company: "EB Pearls",
    location: "Lalitpur, Nepal",
    tags: ["Technology"],
    applicants: 8,
    capacity: 10,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 95000,
    icon: "/jobs/sample.png",
  },
  {
    id: 27,
    title: "SEO Specialist",
    company: "Khalti",
    location: "Lalitpur, Nepal",
    tags: ["Marketing", "SEO"],
    applicants: 4,
    capacity: 5,
    type: "Full Time",
    category: "Marketing",
    level: "Mid",
    salary: 70000,
    icon: "/jobs/sample.png",
  },
  {
    id: 28,
    title: "Network Administrator",
    company: "Nepal Telecom",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 3,
    capacity: 4,
    type: "Full Time",
    category: "Technology",
    level: "Mid",
    salary: 90000,
    icon: "/jobs/sample.png",
  },
  {
    id: 29,
    title: "Video Editor",
    company: "Daraz Nepal",
    location: "Lalitpur, Nepal",
    tags: ["Design", "Media"],
    applicants: 6,
    capacity: 8,
    type: "Contract",
    category: "Design",
    level: "Entry",
    salary: 55000,
    icon: "/jobs/sample.png",
  },
  {
    id: 30,
    title: "Financial Analyst",
    company: "Nabil Bank",
    location: "Kathmandu, Nepal",
    tags: ["Finance"],
    applicants: 3,
    capacity: 2,
    type: "Full Time",
    category: "Finance",
    level: "Mid",
    salary: 95000,
    icon: "/jobs/sample.png",
  },
  {
    id: 31,
    title: "UI/UX Designer",
    company: "Code Himalaya",
    location: "Bhaktapur, Nepal",
    tags: ["Design"],
    applicants: 7,
    capacity: 10,
    type: "Full Time",
    category: "Design",
    level: "Mid",
    salary: 85000,
    icon: "/jobs/sample.png",
  },
  {
    id: 32,
    title: "Blockchain Developer",
    company: "F1Soft International",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 2,
    capacity: 3,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 190000,
    icon: "/jobs/sample.png",
  }
];

export const locations = [
  "Kathmandu, Nepal",
  "Lalitpur, Nepal",
  "Bhaktapur, Nepal",
  "Pokhara, Nepal",
  "Biratnagar, Nepal",
  "Birgunj, Nepal",
];
