export const tagColors = {
  Marketing: "border-[#FFB836] border-[1px] text-[#FFB836]",
  Design: "border-[#4640DE] border-[1px] text-[#4640DE]",
  Technology: "bg-[#FF65501A] text-[#FF6550]",
  "UI Design": "border-[#00B8D9] border-[1px] text-[#00B8D9]",
  Sales: "border-[#36B37E] border-[1px] text-[#36B37E]",
};

export const jobsData = [
  {
    id: 1,
    title: "Social Media Assistant",
    company: "CloudFactory",
    location: "Kathmandu, Nepal",
    tags: ["Design", "Marketing"],
    applicants: 4,
    capacity: 10,
    type: "Full Time",
    category: "Marketing",
    level: "Entry",
    salary: 40000,
    icon: "/jobs/sample.png",
  },
  {
    id: 2,
    title: "Brand Designer",
    company: "Fusemachines",
    location: "Lalitpur, Nepal",
    tags: ["Design"],
    applicants: 2,
    capacity: 10,
    type: "Full Time",
    category: "Design",
    level: "Mid",
    salary: 80000,
    icon: "/jobs/sample.png",
  },
  {
    id: 3,
    title: "Interactive Developer",
    company: "Leapfrog Technology",
    location: "Kathmandu, Nepal",
    tags: ["UI Design"],
    applicants: 6,
    capacity: 10,
    type: "Contract",
    category: "Design",
    level: "Senior",
    salary: 120000,
    icon: "/jobs/sample.png",
  },
  {
    id: 4,
    title: "Email Marketing Specialist",
    company: "Verisk Nepal",
    location: "Bhaktapur, Nepal",
    tags: ["Marketing"],
    applicants: 8,
    capacity: 10,
    type: "Remote",
    category: "Marketing",
    level: "Mid",
    salary: 70000,
    icon: "/jobs/sample.png",
  },
  {
    id: 5,
    title: "Lead Engineer",
    company: "Cotiviti Nepal",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 3,
    capacity: 10,
    type: "Full Time",
    category: "Technology",
    level: "Senior",
    salary: 150000,
    icon: "/jobs/sample.png",
  },
  {
    id: 6,
    title: "Product Designer",
    company: "Deerwalk",
    location: "Lalitpur, Nepal",
    tags: ["Design"],
    applicants: 7,
    capacity: 10,
    type: "Remote",
    category: "Design",
    level: "Senior",
    salary: 110000,
    icon: "/jobs/sample.png",
  },
  {
    id: 7,
    title: "Customer Relationship Manager",
    company: "Nepal Payment Solutions",
    location: "Kathmandu, Nepal",
    tags: ["Marketing"],
    applicants: 5,
    capacity: 10,
    type: "Part Time",
    category: "Marketing",
    level: "Mid",
    salary: 60000,
    icon: "/jobs/sample.png",
  },
  {
    id: 8,
    title: "Frontend Developer",
    company: "F1Soft International",
    location: "Kathmandu, Nepal",
    tags: ["Technology"],
    applicants: 9,
    capacity: 10,
    type: "Remote",
    category: "Technology",
    level: "Senior",
    salary: 130000,
    icon: "/jobs/sample.png",
  },
  {
    id: 9,
    title: "Marketing Intern",
    company: "Daraz Nepal",
    location: "Bhaktapur, Nepal",
    tags: ["Marketing"],
    applicants: 1,
    capacity: 10,
    type: "Internship",
    category: "Marketing",
    level: "Entry",
    salary: 20000,
    icon: "/jobs/sample.png",
  },
  {
    id: 10,
    title: "Sales Representative",
    company: "CG Corp Global",
    location: "Lalitpur, Nepal",
    tags: ["Sales"],
    applicants: 4,
    capacity: 10,
    type: "Full Time",
    category: "Sales",
    level: "Mid",
    salary: 75000,
    icon: "/jobs/sample.png",
  },
];

export const locations = [
  "Kathmandu, Nepal",
  "Lalitpur, Nepal",
  "Bhaktapur, Nepal",
  "Pokhara, Nepal",
  "Biratnagar, Nepal",
  "Birgunj, Nepal",
];
